export const API_PUBLIC_KEY = process.env.VITE_VERCEL_PUBLIC_API_PUBLIC_KEY;
export const COLLECTION_ID = process.env.VITE_VERCEL_PUBLIC_COLLECTION_ID;
export const BASE_URL = process.env.VITE_VERCEL_PUBLIC_BASE_URL;

